# Generated by Django 6.1.1 on 2026-09-29 22:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "Tag",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid8,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=500, unique=True)),
                ("content", models.TextField(max_length=50000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tag",
                    models.ManyToManyField(
                        db_index=True, related_name="tags", to="blog.tag"
                    ),
                ),
            ],
            options={
                "db_table": "Article",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["uuid", "title"], name="Article_uuid_364157_idx"
                    )
                ],
            },
        ),
    ]
