# Generated by Django 6.1.1 on 2026-09-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_visible",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the article is hidden; otherwise it is visible.",
            ),
        ),
    ]
