# Generated by Django 6.1.1 on 2026-09-29 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_article_is_visible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="tag",
            new_name="tags",
        ),
    ]
