# Generated by Django 6.1.1 on 2026-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_tag_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                db_index=True, related_name="articles", to="blog.tag"
            ),
        ),
    ]
