# Generated by Django 6.1.1 on 2026-10-02 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_article_tags"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="article",
            name="Article_uuid_364157_idx",
        ),
    ]
