# Generated by Django 6.1.1 on 2026-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_remove_article_article_uuid_364157_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["is_visible", "-created_at"], name="Article_is_visi_07a4b1_idx"
            ),
        ),
    ]
