# Generated by Django 6.1.1 on 2026-10-02 14:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_article_article_is_visi_07a4b1_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_visible",
            field=models.BooleanField(
                default=False,
                help_text="If checked, the article is publicly visible; otherwise it is hidden.",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(related_name="articles", to="blog.tag"),
        ),
        migrations.AlterField(
            model_name="article",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
